### ISSUE TITLE
Numpy v2 support

### ISSUE THREAD

**Issue by maresb** [mercator-ocean/copernicus-marine-toolbox#159]
I would like to be able to use the Python API in Python environments that I have already upgraded to Numpy v2. Currently I can't do this with a release version due to https://github.com/mercator-ocean/copernicus-marine-toolbox/blob/3dee4b5b5c978e0a7647efd888be6cd9c78ba7b6/pyproject.toml#L27

The [version notes](https://help.marine.copernicus.eu/en/articles/8218641-next-milestones-and-roadmap) for v1.3.1 mention https://github.com/pydata/xarray/issues/9179 as blocking, but it has since been merged and released.

Before finding this repo on GitHub I chatted with Leïla on the website. She pointed me to https://github.com/pydata/xarray/issues/9545, which seems to be a performance regression.

**Question:** If I were to unpin `numpy<2` on my fork (using `v1.3.3` by default, or possibly another tag), pin to the latest xarray, and accept the performance regression, are there any other blockers or potential for incorrect data that I should be aware of?

**Comment by veenstrajelmer** [comment]
Besides your question, I think it is good if copernicusmarine would support numpy v2 soon. This is also one of the blockers for python 3.13 support: https://github.com/mercator-ocean/copernicus-marine-toolbox/issues/158

**Comment by renaudjester** [comment]
Hi @maresb,

Indeed it's a performance regression that should be fixed in the next release of xarray. It basically add 5 seconds every time you do: `xarray.open_dataset`

We haven't noticed any other problems. However, it hasn't been extensively tested as we discovered the two bugs one after the other. And the first one was on the data itself (no errors or anything). 

So theoretically, yeah you are good to go if you accept the performance regression! 

Don't hesitate to report any other issues you find :D

**Comment by veenstrajelmer** [comment]
@renaudjester could you link the relevant xarray issue/PR please?

**Comment by maresb** [comment]
I haven't tested this so thoroughly, but so far it seems like it's working. In case anyone else wants to give this a try:

```bash
pip install maresb-copernicusmarine-unpin-numpy
```
